// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	typesFieldNames          = builder.RawFieldNames(&Types{})
	typesRows                = strings.Join(typesFieldNames, ",")
	typesRowsExpectAutoSet   = strings.Join(stringx.Remove(typesFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	typesRowsWithPlaceHolder = strings.Join(stringx.Remove(typesFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheBiggerStrongerTypesIdPrefix = "cache:biggerStronger:types:id:"
)

type (
	typesModel interface {
		Insert(ctx context.Context, data *Types) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Types, error)
		Update(ctx context.Context, data *Types) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTypesModel struct {
		sqlc.CachedConn
		table string
	}

	Types struct {
		Id     int64  `db:"id"`
		Name   string `db:"name"`
		Parent int64  `db:"parent"`
	}
)

func newTypesModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultTypesModel {
	return &defaultTypesModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`types`",
	}
}

func (m *defaultTypesModel) Insert(ctx context.Context, data *Types) (sql.Result, error) {
	biggerStrongerTypesIdKey := fmt.Sprintf("%s%v", cacheBiggerStrongerTypesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, typesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Parent)
	}, biggerStrongerTypesIdKey)
	return ret, err
}

func (m *defaultTypesModel) FindOne(ctx context.Context, id int64) (*Types, error) {
	biggerStrongerTypesIdKey := fmt.Sprintf("%s%v", cacheBiggerStrongerTypesIdPrefix, id)
	var resp Types
	err := m.QueryRowCtx(ctx, &resp, biggerStrongerTypesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", typesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTypesModel) Update(ctx context.Context, data *Types) error {
	biggerStrongerTypesIdKey := fmt.Sprintf("%s%v", cacheBiggerStrongerTypesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, typesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Parent, data.Id)
	}, biggerStrongerTypesIdKey)
	return err
}

func (m *defaultTypesModel) Delete(ctx context.Context, id int64) error {
	biggerStrongerTypesIdKey := fmt.Sprintf("%s%v", cacheBiggerStrongerTypesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, biggerStrongerTypesIdKey)
	return err
}

func (m *defaultTypesModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheBiggerStrongerTypesIdPrefix, primary)
}

func (m *defaultTypesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", typesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTypesModel) tableName() string {
	return m.table
}
