// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Account  string `json:"account"`  // 账号
	Password string `json:"password"` // 密码
}

type LoginResp struct {
	Token string `json:"token"` // 登录令牌
}

type StatisticResp struct {
	Users       int64 `json:"users"`       // 用户数
	Questions   int64 `json:"questions"`   // 题库数
	Types       int64 `json:"types"`       // 题库类型数
	TodayAnswer int64 `json:"todayAnswer"` // 今日答题次数
}

type CaptchaReq struct {
	Account string `form:"account"` //	账户
}

type CaptchaResp struct {
	ImageBase64 string `json:"imageBase64"` //	主图的base64
	ThumbBase64 string `json:"thumbBase64"` // 	校验图base64
	CaptchaKey  string `json:"captchaKey"`  //	验证码KEY
}

type CheckCaptchaReq struct {
	Dots string `json:"dots"` //	位置信息
	Key  string `json:"key"`  //	验证码key
}

type ImportReq struct {
	File string `form:"file,optional"`
}

type AddReq struct {
	Type    int64  `json:"type"`    // 所属题库类型
	Desc    string `json:"desc"`    // 题目描述
	Options string `json:"options"` // 题目选项
	Answers string `json:"answers"` // 题目答案
	Summary string `json:"summary"` // 题目考点
}

type EditReq struct {
	Id      int64  `json:"id"`
	Type    int64  `json:"type"`    // 所属题库类型
	Desc    string `json:"desc"`    // 题目描述
	Options string `json:"options"` // 题目选项
	Answers string `json:"answers"` // 题目答案
	Summary string `json:"summary"` // 题目考点
}

type DeleteReq struct {
	Ids []int64 `json:"ids"`
}

type ListReq struct {
	Type    int64  `json:"type"`    // 所属题库类型
	Keyword string `json:"keyword"` // 题目关键词查询
	Page    int    `json:"page"`    // 页码
	Size    int    `json:"size"`    // 大小
}

type ListResp struct {
	Total     int64      `json:"total"`
	Questions []Question `json:"questions"`
}

type Question struct {
	Id         int64  `json:"id"`
	Desc       string `json:"desc"`       // 题目描述
	Options    string `json:"options"`    // 题目选项
	Answers    string `json:"answers"`    // 题目答案
	Summary    string `json:"summary"`    // 题目考点
	Stat       string `json:"stat"`       // 正确率
	CreateTime int64  `json:"createTime"` // 创建时间
}

type AnalyzingReq struct {
}

type AnalyzingResp struct {
}

type TypeAddReq struct {
	Type int64  `json:"type"` // 所属题库类型
	Name string `json:"name"` // 题库名
}

type TypeEditReq struct {
	Id   int64  `json:"id"`
	Type int64  `json:"type"` // 所属题库类型
	Name string `json:"name"` // 题库名
}

type TypeOptionResp struct {
	Items []Type `json:"items"`
}

type Type struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Items []Type `json:"items"`
}

type TypeDeleteReq struct {
	Id int64 `json:"id"`
}

type UserAddReq struct {
	Name   string `json:"name"`
	OpenId string `json:"openId"`
}

type UserInfoReq struct {
	OpenId string `json:"openId"` //微信openID
}

type UserInfoResp struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`   // 用户名称 默认微信名称
	OpenId string `json:"openId"` //微信openID
	Count  int64  `json:"count"`  // 答题次数
	State  string `json:"state"`  // 答题统计 正确数/总数
}

type UserListReq struct {
	Name string `json:"name"`
	Page int    `json:"page"` // 页码
	Size int    `json:"size"` // 大小
}

type UserListResp struct {
	Id             int64  `json:"id"`
	Name           string `json:"name"`           // 用户名称 默认微信名称
	OpenId         string `json:"openId"`         //微信openID
	Count          int64  `json:"count"`          // 答题次数
	State          string `json:"state"`          // 答题统计 正确数/总数
	LastAnswerTime int64  `json:"lastAnswerTime"` // 上次答题时间
}
